//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoresIniCreator {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_ruRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_ruRu() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoresIniCreator.Messages_ruRu", typeof(Messages_ruRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при чтении данных из конфигурационного файла. Проверьте файл на соответствие формату и наличие необходимых параметров. Оригинальное сообщение: .
        /// </summary>
        internal static string configFileException {
            get {
                return ResourceManager.GetString("configFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, нажмите Enter для выхода из программы....
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла критическая ошибка. Приложение будет закрыто. Оригинальное сообщение:.
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в StoresIniCreator!.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение файловой переменной не может быть null или файл не существует..
        /// </summary>
        internal static string iniCreatorCtorFileException {
            get {
                return ResourceManager.GetString("iniCreatorCtorFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение входного параметра имеет недопустимое значение..
        /// </summary>
        internal static string iniCreatorCtorNumericException {
            get {
                return ResourceManager.GetString("iniCreatorCtorNumericException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Считывание данных завершено на: .
        /// </summary>
        internal static string percentOfReadProcess {
            get {
                return ResourceManager.GetString("percentOfReadProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обрабатывается запись о ПБО: .
        /// </summary>
        internal static string storeProcessingStatus {
            get {
                return ResourceManager.GetString("storeProcessingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка доступа к файлу. Возможно необходый файл доступен только для чтения. Оригинальное сообщение:.
        /// </summary>
        internal static string unauthorizedAccessException {
            get {
                return ResourceManager.GetString("unauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Считывание данных из vpn_objects завершено..
        /// </summary>
        internal static string vpnObjectsFileFinishRead {
            get {
                return ResourceManager.GetString("vpnObjectsFileFinishRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл vpn_objects не найден в указанной директории!.
        /// </summary>
        internal static string vpnObjectsFileNotFound {
            get {
                return ResourceManager.GetString("vpnObjectsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинаем считывание данных из vpn_objects..
        /// </summary>
        internal static string vpnObjectsFileStartRead {
            get {
                return ResourceManager.GetString("vpnObjectsFileStartRead", resourceCulture);
            }
        }
    }
}
